on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

    # Axis.Sigma.Command
    - name: Pack
      run: dotnet pack ./Axis.Sigma/Axis.Sigma.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Axis.Sigma.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_TOKEN }}